# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8df8024fd2bee621adc44f69c833eee5857c46b192e120e21b15e708895d954c10483d8c0f0a7e20b82970b8cafa832bdf1eae3898bf0d49ed85ce591074bbb7

test:
  secret_key_base: a8266631feaa125a2036ec98b5441ca28ca325bd6d2d8bc5750c4281fafb909bebe0c404054d51439323623aa3342756d50d747c5ea8cb29f6402d0491734e44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
